name: Debug token discord 

on:
  push:
    branches:
      - master  # Запускать пайплайн при пуше в ветку master
  pull_request:
    branches:
      - master  # Запускать пайплайн при создании PR в ветку master

jobs:
    steps:
      - name: Debug environment variables
        run: |
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}"
          echo "DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN"